# Generated by Django 4.0.2 on 2022-02-25 12:04

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courier1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_quote',
            fields=[
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Source_pincode', models.IntegerField(max_length=25)),
                ('Destination_pincode', models.IntegerField(max_length=25)),
                ('Package_size', models.CharField(max_length=25)),
                ('Category', models.CharField(max_length=25)),
                ('Package_value', models.IntegerField(max_length=25)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('Address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('Address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
            ],
        ),
    ]
